version: '3.8'

services:

  producer:
    restart: on-failure
    build:
      no_cache: true
      dockerfile: producer/Producer/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - default-network
    environment:
      ProducerConfig__BootstrapServers: kafka:29092

  web:
    restart: on-failure
    build:
      no_cache: true
      dockerfile: producer/Web/Dockerfile
    ports:
      - "5050:5000"
    networks:
      - default-network
    environment:
      MinioOptions__Endpoint: host.docker.internal:9000
      MinioOptions__AccessKey: x4gPrlZuzDT8Ms7duYGQ
      MinioOptions__SecretKey: c290oswm6rVgvGnNZ2EnJ2RpkkAZsDVDqmjkkWGw

networks: 
  default-network:
    driver: bridge 
