version: '3.8'

services:

  producer:
    restart: on-failure
    build:
      no_cache: true
      dockerfile: producer/Producer/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - default-network
    environment:
      Trackers__0__Type: PostgreSql
      Trackers__0__Configuration__ConnectionString: Server=host.docker.internal;Port=5432;Database=masters;User ID=postgres;Password=postgres
      MinioOptions__Endpoint: host.docker.internal:9000
      MinioOptions__AccessKey: oESO3J9hOl6Xd2IBIrOz
      MinioOptions__SecretKey: Qz4OXPf0FEEKyaDak50SrIL1yx4Wp3MH0qRSUqg6
      ProducerConfig__BootstrapServers: kafka:29092
      ConsumerConfig__BootstrapServers: kafka:29092
      ConsumerConfig__GroupId: client
      ConsumerConfig__AutoOffsetReset: Earliest
      DatabaseOptions__ConnectionString: Server=host.docker.internal;Port=5432;Database=masters;User ID=postgres;Password=postgres

  web:
    restart: on-failure
    build:
      no_cache: true
      dockerfile: producer/Web/Dockerfile
    ports:
      - "5050:5000"
    networks:
      - default-network
    environment:
      MinioOptions__Endpoint: host.docker.internal:9000
      MinioOptions__AccessKey: oESO3J9hOl6Xd2IBIrOz
      MinioOptions__SecretKey: Qz4OXPf0FEEKyaDak50SrIL1yx4Wp3MH0qRSUqg6
      DatabaseOptions__ConnectionString: Server=host.docker.internal;Port=5432;Database=masters;User ID=postgres;Password=postgres

networks: 
  default-network:
    driver: bridge 
